apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: backoffice-system
  title: Backoffice System
  description: Handles internal operations like shipment logistics and invoice management.
  annotations:
    gitlab.com/project-slug: ch-mc-b/autoshop-ms/app/backoffice
    backstage.io/source-location: url:https://gitlab.com/ch-mc-b/autoshop-ms/app/backoffice
    backstage.io/techdocs-ref: url:https://gitlab.com/ch-mc-b/autoshop-ms/app/backoffice   
spec:
  owner: backoffice-team

---
# shipment
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backoffice-shipment
  description: Handles shipping logistics.
  annotations:
    backstage.io/kubernetes-id: shipment    
    gitlab.com/project-slug: ch-mc-b/autoshop-ms/app/backoffice  
spec:
  type: service
  lifecycle: production
  owner: backoffice-team
  system: backoffice-system
  dependsOn:
    - component:default/shop-webshop  

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backoffice-shipment-api
spec:
  type: openapi
  lifecycle: production
  owner: backoffice-team
  system: backoffice-system
  definition: 
    $text: ./openapi/shipment.yaml
  providesApis:
    - backoffice-shipment-api

# invoicing
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backoffice-invoicing
  description: Invoice generation and processing.
  annotations:
    backstage.io/kubernetes-id: invoicing    
    gitlab.com/project-slug: ch-mc-b/autoshop-ms/app/backoffice   
spec:
  type: service
  lifecycle: production
  owner: backoffice-team
  system: backoffice-system
  dependsOn:
    - component:default/shop-webshop  

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backoffice-invoicing-api
spec:
  type: openapi
  lifecycle: production
  owner: backoffice-team
  system: backoffice-system
  definition: 
    $text: ./openapi/invoicing.yaml
  providesApis:
    - backoffice-invoicing-api
